// react-app/src/pages/Register.tsx
import React, { useState } from 'react';
import AuthService from '../services/AuthService';
import { useNavigate } from 'react-router-dom';

const Register: React.FC = () => {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [errors, setErrors] = useState<string[]>([]);
  const [checking, setChecking] = useState(false);
  const [available, setAvailable] = useState(false);
  const [checked, setChecked] = useState(false);
  const [metComplexity, setMetComplexity] = useState(true);
  const navigate = useNavigate();

  const onEmailChange = async (val: string) => {
    setEmail(val);
    setChecking(true);
    try {
      const exists = await AuthService.userExists(val);
      setAvailable(!exists);
      setChecked(true);
    } finally {
      setChecking(false);
    }
  };

  const onPasswordChange = async (val: string) => {
    setPassword(val);
    try {
      const result = await AuthService.checkPasswordComplexity(val);
      setMetComplexity(result.success);
      setErrors(result.errors || []);
    } catch {
      setErrors(['Unable to validate password']);
    }
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrors([]);
    try {
      await AuthService.register({
        firstName,
        lastName,
        emailAddress: email,
        username: email,
        password,
        confirmPassword,
      });
      alert('Registration successful. Please log in.');
      navigate('/login');
    } catch (err: any) {
      if (err.response?.data?.errors) setErrors(err.response.data.errors);
      else alert('Registration failed');
    }
  };

  return (
    <div className="row justify-content-center">
      <div className="col-md-6">
        <h2 className="text-center">Register</h2>
        {errors.length > 0 && (
          <div className="alert alert-warning">
            <ul>{errors.map((e, i) => (<li key={i}>{e}</li>))}</ul>
          </div>
        )}
        <form onSubmit={onSubmit}>
          <div className="mb-3">
            <label className="form-label">Email</label>
            <input type="email" className="form-control" value={email} onChange={e => onEmailChange(e.target.value)} required />
            {checked && !available && <div className="text-danger">Email already in use.</div>}
          </div>
          <div className="mb-3">
            <label className="form-label">First Name</label>
            <input type="text" className="form-control" value={firstName} onChange={e => setFirstName(e.target.value)} required />
          </div>
          <div className="mb-3">
            <label className="form-label">Last Name</label>
            <input type="text" className="form-control" value={lastName} onChange={e => setLastName(e.target.value)} required />
          </div>
          <div className="mb-3">
            <label className="form-label">Password</label>
            <input type="password" className="form-control" value={password} onChange={e => onPasswordChange(e.target.value)} required />
            {!metComplexity && <div className="text-danger">Password doesn't meet complexity.</div>}
          </div>
          <div className="mb-3">
            <label className="form-label">Confirm Password</label>
            <input type="password" className="form-control" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} required />
            {confirmPassword !== password && <div className="text-danger">Passwords must match.</div>}
          </div>
          <button type="submit" className="btn btn-primary" disabled={!available || password !== confirmPassword || !metComplexity || checking}>Register</button>
        </form>
      </div>
    </div>
  );
};

export default Register;

// ng-app/src/app/account/register/register.component.ts
import { Component } from '@angular/core';
import { RestService } from '../../core/_services/rest.service';
import { LoggerService } from '../../core/_services/logger.service';
import { Router } from '@angular/router';
import { AuthService } from '../../core/_services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss'],
})
export class RegisterComponent {
  model = {
    firstName: '',
    lastName: '',
    emailAddress: '',
    username: '',
    password: '',
    confirmPassword: '',
  };

  usernameAvailable = false;
  checkingUsername = false;
  checkedUsername = false;
  usernameValid = false;
  checkedComplexity = false;
  metComplexityStandard = false;

  constructor(
    private auth: AuthService,
    private logger: LoggerService,
    private rest: RestService,
    private router: Router
  ) {}

  onEmailAddressChanged(newEmailAddress: string) {
    this.model.username = newEmailAddress;
    this.usernameValid = validateEmail(newEmailAddress);
    if (!this.usernameValid) return;

    this.checkingUsername = true;
    let url = 'Auth/UserExists?username=' + newEmailAddress;
    this.rest.getResource(url).subscribe((data: any) => {
      this.checkedUsername = true;
      this.checkingUsername = false;
      this.usernameAvailable = !data.exists;
    });

    function validateEmail(email: any) {
      // tslint:disable-next-line:max-line-length
      const re =
        /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return re.test(String(email).toLowerCase());
    }
  }

  onPasswordChanged() {
    this.auth
      .checkPasswordComplexity(this.model.password)
      .subscribe((data: any) => {
        this.checkedComplexity = true;
        this.metComplexityStandard = data.success;
      });
  }

  onSubmit() {
    console.log('Registration form submitted:', this.model);
    let url = 'Auth/Register';
    this.rest.postResource(url, this.model).subscribe(
      (data: any) => {
        this.router.navigateByUrl('/account/register-confirmation');

        console.log('Done:', data);
      },
      (err: any) => {
        this.logger.error('An error occurred. ' + err);
      }
    );
  }

  showSuccess() {
    this.logger.success('Hey!');
  }

  showWarning() {
    this.logger.warning('Hey!');
  }

  showDanger() {
    this.logger.error('Hey!');
  }
}

<div class="container mat-container padded-top">
  <mat-card class="mat-card">
    <h3 class="mat-title text-center">Register</h3>
    <form (ngSubmit)="onSubmit()" #theform="ngForm" class="form">
      <app-username-email-input
        [emailAddress]="model.username"
        [available]="usernameAvailable"
        [checking]="checkingUsername"
        [checked]="checkedUsername"
        [valid]="usernameValid"
        [labelText]="'Email Address'"
        (emailAddressUpdated)="onEmailAddressChanged($event)"
      ></app-username-email-input>

      <mat-form-field class="form-field" appearance="fill">
        <mat-label>First Name</mat-label>
        <input
          matInput
          type="text"
          placeholder="Enter your first name"
          [(ngModel)]="model.firstName"
          name="firstName"
          required
        />
        <mat-error *ngIf="!model.firstName"
          >Please enter your first name.</mat-error
        >
      </mat-form-field>

      <mat-form-field class="form-field" appearance="fill">
        <mat-label>Last Name</mat-label>
        <input
          matInput
          type="text"
          placeholder="Enter your last name"
          [(ngModel)]="model.lastName"
          name="lastName"
          required
        />
        <mat-error *ngIf="!model.lastName"
          >Please enter your last name.</mat-error
        >
      </mat-form-field>

      <mat-form-field class="form-field" appearance="fill">
        <mat-label>Password</mat-label>
        <input
          matInput
          type="password"
          placeholder="Enter your password"
          [(ngModel)]="model.password"
          (change)="onPasswordChanged()"
          name="password"
          required
        />
        <mat-error *ngIf="!model.password"
          >Please enter your password.</mat-error
        >
        <!-- ZOMBIE: Why doesn't this work?
         <mat-error *ngIf="checkedComplexity && !metComplexityStandard">
          Password doesn't meet complexity standards
        </mat-error> 
        -->
        <mat-hint
          style="color: red"
          *ngIf="checkedComplexity && !metComplexityStandard"
        >
          Password doesn't meet complexity standards
        </mat-hint>
      </mat-form-field>

      <mat-form-field class="form-field" appearance="fill">
        <mat-label>Confirm Password</mat-label>
        <input
          matInput
          type="password"
          placeholder="Confirm your password"
          [(ngModel)]="model.confirmPassword"
          name="confirmPassword"
          required
        />
        <mat-error *ngIf="model.confirmPassword !== model.password">
          Passwords must match.
        </mat-error>
      </mat-form-field>

      <button
        mat-raised-button
        color="primary"
        class="submit-button"
        type="submit"
        [disabled]="
          theform.invalid ||
          !usernameValid ||
          !usernameAvailable ||
          !metComplexityStandard
        "
      >
        Register
      </button>
    </form>
  </mat-card>
</div>
