// ng-app/src/app/home/home.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { CardMenuItem } from '../shared/card-menu/card-menu.component';
import { AppConfig, AppUser } from '../_api';
import { APP_CONFIG } from '../core/_services/config-injection';
import { RestService } from '../core/_services/rest.service';
import { LoggerService } from '../core/_services/logger.service';
import { CurrentUserService } from '../core/_services/current-user.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent implements OnInit {
  appUser: AppUser;
  loggedIn: boolean | undefined = undefined;

  menuItems: CardMenuItem[] = [
    {
      title: 'Home',
      description: 'You are here',
      icon: 'fa fa-home',
    },
  ];

  constructor(
    @Inject(APP_CONFIG) public config: AppConfig,
    private currentUser: CurrentUserService,
    private logger: LoggerService,
    private rest: RestService
  ) {}

  ngOnInit(): void {
    this.loggedIn = this.currentUser.isLoggedIn();
    this.currentUser.getAppUser().subscribe((data: AppUser) => {
      this.appUser = data;
    });
  }

  testSecureEndpoint() {
    this.rest.getResource('Secure/GetColorList').subscribe(
      (data) => {
        console.log('Success', data);
        this.logger.success('That endpoint worked!');
      },
      (err) => {
        console.log('Error', err);
        this.logger.error('That endpoint threw an error.');
      }
    );
  }
}

<mat-card>
  <mat-card-header>
    <mat-card-title>Welcome to the SimpleAuthNet</mat-card-title>
    <mat-card-subtitle
      >Making Auth Suck Less in .NET 9 WebApi and Angular</mat-card-subtitle
    >
  </mat-card-header>
  <mat-card-content>
    <div
      *ngIf="loggedIn == false"
      class="alert alert-warning padded-top padded-bottom"
    >
      You are NOT logged in.
      <a routerLink="/account/login">Log in</a>
    </div>

    <div
      *ngIf="loggedIn == true && appUser"
      class="alert alert-success padded-top padded-bottom"
    >
      You are logged in as {{ appUser.username }}.
      <a routerLink="/account/logout">Log out</a>
    </div>

    <div class="padded-top">
      <app-card-menu [menuItems]="menuItems"></app-card-menu>
    </div>
  </mat-card-content>
</mat-card>

<mat-card class="padded-top">
  <mat-card-header>
    <mat-card-title>Test Area</mat-card-title>
    <mat-card-subtitle
      >Use the buton below to test the secured endpoint.</mat-card-subtitle
    >
  </mat-card-header>
  <mat-card-content> </mat-card-content>
  <mat-card-actions>
    <button mat-raised-button (click)="testSecureEndpoint()">
      Test Secure Resource
    </button>
  </mat-card-actions>
</mat-card>

// react-app/src/pages/Home.tsx
import React, { useEffect, useState } from 'react';
import AuthService from '../services/AuthService';

const Home: React.FC = () => {
  const [loggedIn, setLoggedIn] = useState<boolean>(false);
  const [apiUrl, setApiUrl] = useState<string>('');

  useEffect(() => {
    setLoggedIn(AuthService.isLoggedIn());
    setApiUrl(AuthService.getApiUrl());
  }, []);

  const handleTestSecureEndpoint = async () => {
    try {
      const response = await fetch(`${apiUrl}Item/GetColorList`, {
        method: 'GET',
        credentials: 'include',
      });
      if (response.ok) {
        alert('Secure endpoint accessed successfully!');
      } else {
        alert('Failed to access secure endpoint.');
      }
    } catch (error) {
      console.error('Error accessing secure endpoint:', error);
      alert('Error accessing secure endpoint.');
    }
  };

  const handleLogout = async () => {
    await AuthService.logout();
    setLoggedIn(false);
  };

  return (
    <div className="container">
      <div className="card mt-3">
        <div className="card-header">
          <h3>Welcome to SimpleAuthNet</h3>
          <p>Making Auth Suck Less in .NET 9 WebApi and React</p>
        </div>
        <div className="card-body">
          {!loggedIn && (
            <div className="alert alert-warning">
              You are NOT logged in. <a href="/login">Log in</a>
            </div>
          )}
          {loggedIn && (
            <div className="alert alert-success">
              You are logged in. <button onClick={handleLogout}>Log out</button>
            </div>
          )}
        </div>
      </div>

      <div className="card mt-3">
        <div className="card-header">
          <h4>Test Area</h4>
          <p>Use the button below to test the secured endpoint.</p>
        </div>
        <div className="card-body">
          <button className="btn btn-primary" onClick={handleTestSecureEndpoint}>
            Test Secure Resource
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
